apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
spec:
  selector:
    app: wisecow
  ports:
    - protocol: TCP
      port: 80       # External port
      targetPort: 4499 # Port on the container
  type: NodePort  # Use NodePort for exposing service in Minikube
