apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
  namespace: default
  labels:
    app: wisecow
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
      - name: wisecow
        image: sandeep3414/wisecow:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4499
        resources:
          limits:
            cpu: "520m"
            memory: "128Mi"
          requests:
            cpu: "250m"
            memory: "64Mi"
