name: CI/CD Workflow

on:
  push:
    branches:
      - main      # Trigger on changes to the main branch
    paths:
      - '**/*.yaml'  # Trigger for YAML files (for deployments or Kubernetes configs)
      - '**/*.dockerfile'  # Trigger for Dockerfile changes

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        run: |
          docker build -t sandeep3414/wisecow:${{ github.sha }} .
          docker push sandeep3414/wisecow:${{ github.sha }}

  deploy_to_kubernetes:
    needs: build_and_push  # Ensure this runs after the build_and_push job is successful
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1  # Change to your region

      - name: Install kubectl
        run: |
          curl -o kubectl https://amazon-eks.s3.ap-south-1.amazonaws.com/1.21.1/2021-07-30/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          mv ./kubectl /usr/local/bin

      - name: Configure kubeconfig for EKS
        run: |
          aws eks --region ap-south-1 update-kubeconfig --name wisecow-cluster
          
      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/wisecow-deployment wisecow=sandeep3414/wisecow:${{ github.sha }} --record
          kubectl rollout status deployment/wisecow-deployment

      - name: Verify deployment
        run: |
          kubectl get pods
          kubectl get svc
