name: CI/CD Workflow

on:
  push:
    branches:
      - main      # Trigger on changes to the main branch
    paths:
      - '**/*.yaml'  # Trigger for YAML files (for deployments or Kubernetes configs)
      - '**/*.dockerfile'  # Trigger for Dockerfile changes

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        run: |
          docker build -t sandeep3414/wisecow:${{ github.sha }} .
          docker push sandeep3414/wisecow:${{ github.sha }}

  deploy_to_kubernetes:
    needs: build_and_push  # Ensure this runs after the build_and_push job is successful
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v2
        with:
          version: 'latest'

      - name: Configure Kubernetes
        run: |
          kubectl config set-cluster my-cluster --server=https://<API_SERVER_URL>
          kubectl config set-credentials my-user --token=${{ secrets.KUBE_TOKEN }}
          kubectl config set-context my-context --cluster=my-cluster --user=my-user
          kubectl config use-context my-context

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/wisecow-deployment wisecow=sandeep3414/wisecow:${{ github.sha }} --record
          kubectl rollout status deployment/wisecow-deployment

      - name: Verify deployment
        run: |
          kubectl get pods
